name: Print stats

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository path'
        required: true
        type: string
        default: 'AdguardTeam/AdguardFilters'
      since:
        description: 'Timestamp to search from'
        required: true
        type: string
        default: '2022-05-01T00:00:00Z'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Print repo stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COLLECTION_PATH: ./events_collection.json
        run: >
          REPO=${{ github.event.inputs.repo }}
          SINCE=${{ github.event.inputs.since }}
          ./bin/github-stats.js
